[build-system]
requires = [
    "levenshtein==0.12.0",
    "PyQt6==6.3.0",
    "PyQt6-Qt6==6.3.0",
    "PyQt6-sip==13.3.1",
    "requests==2.25.1",
    "wikipedia==1.4.0",
]
build-backend = "setuptools.build_meta"